finalProjectDjangoWeb1/webserver/drone_setup/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'drone_setup'

urlpatterns = [
    url(r'^$', views.drone_setup, name='drone_setup'),
    url(r'^progress/', views.progress_bar, name='progress_bar'),
    url(r'^setup_result/', views.setup_result, name='setup_result'),
    url(r'^setup_params/', views.setup_params, name='setup_params')
]

finalProjectDjangoWeb1/webserver/flight_monitor/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'flight_monitor'

urlpatterns = [
    url(r'^$', views.flight_monitor, name='flight_monitor'),
    url(r'^get_current_flights$', views.update_flight_table, name='get_current_flights'),
    url(r'^flight_monitor_js$', views.flight_monitor_js, name='flight_monitor_js'),
    url(r'^pop_up_modal_header', views.pop_up_modal_header, name='pop_up_modal_header'),
    url(r'^pop_up_modal_body', views.pop_up_modal_body, name='pop_up_modal_body'),
    url(r'^pop_up_modal$', views.pop_up_modal, name='pop_up_modal'),
    url(r'^pop_up_modal_close', views.pop_up_modal_close, name='pop_up_modal_close'),
    url(r'^save_comment', views.save_comment, name='save_comment'),
]

finalProjectDjangoWeb1/webserver/index/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'index'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^get_flight_status/', views.get_flight_status, name='get_flight_status'),
]

finalProjectDjangoWeb1/webserver/management/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'management'

urlpatterns = [
    url(r'^$', views.manage, name='management'),
    url(r'^get_table/', views.get_table, name='get_table'),
    url(r'^table_update/', views.table_update, name='table_update'),
    url(r'^motor_table_update/', views.motor_table_update, name='motor_table_update'),
    url(r'^get_motor_table/', views.get_motor_table, name='get_motor_table'),
    url(r'^add_single_motor_table/', views.add_single_motor_table, name='add_single_motor_table'),
    url(r'^add_multi_motor_table/', views.add_multi_motor_table, name='add_multi_motor_table'),
    url(r'^delete_motor_table/', views.delete_motor_table, name='delete_motor_table'),
    url(r'^bat_table_update/', views.bat_table_update, name='bat_table_update'),
    url(r'^get_bat_table/', views.get_bat_table, name='get_bat_table'),
    url(r'^add_single_bat_table/', views.add_single_bat_table, name='add_single_bat_table'),
    url(r'^add_multi_bat_table/', views.add_multi_bat_table, name='add_multi_bat_table'),
    url(r'^delete_bat_table/', views.delete_bat_table, name='delete_bat_table'),
    url(r'^prop_table_update/', views.prop_table_update, name='prop_table_update'),
    url(r'^get_prop_table/', views.get_prop_table, name='get_prop_table'),
    url(r'^add_single_prop_table/', views.add_single_prop_table, name='add_single_prop_table'),
    url(r'^add_multi_prop_table/', views.add_multi_prop_table, name='add_multi_prop_table'),
    url(r'^delete_prop_table/', views.delete_prop_table, name='delete_prop_table'),
    url(r'^drone_table_update/', views.drone_table_update, name='prop_table_update'),
    url(r'^get_drone_table/', views.get_drone_table, name='get_prop_table'),
]

finalProjectDjangoWeb1/webserver/reviews/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'reviews'

urlpatterns = [
    url(r'^$', views.review, name='reviews'),
    url(r'^update_reviews/', views.update_review2, name='update_reviews'),
    url(r'^pop_up_modal/', views.pop_up_modal, name='pop_up_modal'),
    url(r'^pop_up_report_modal/', views.pop_up_report_modal, name='pop_up_modal'),
    url(r'^get_flights_per_drone/', views.get_flights_per_drone, name='get_flights_per_drone'),
    url(r'^get_errors_per_drone/', views.get_errors_per_drone, name='get_flights_per_drone'),
    url(r'^get_all_errors/', views.get_all_errors, name='get_all_errors'),
    url(r'^get_flights_per_month/', views.get_flights_per_month, name='get_flights_per_month'),
    url(r'^get_errors_per_month/', views.get_errors_per_month, name='get_errors_per_month'),
    url(r'^get_total_flight_time_per_drone/', views.get_total_flight_time_per_drone, name='get_total_flight_time_per_drone'),
]

finalProjectDjangoWeb1/webserver/webserver/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import sys

sys.path.append('../')
import controller

controller.get_instance()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('index.urls', namespace="index")),
    url(r'^flight_monitor/', include('flight_monitor.urls', namespace="flight_monitor")),
    url(r'^drone_setup/', include('drone_setup.urls', namespace="drone_setup")),
    url(r'^reviews/', include('reviews.urls', namespace="reviews")),
    url(r'^management/', include('management.urls', namespace="management")),
]

finalProjectDjangoWeb1/webserver/flight_monitor/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

finalProjectDjangoWeb1/webserver/flight_monitor/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpRequest
from django.shortcuts import redirect
from django.core.urlresolvers import reverse, reverse_lazy, resolve
from django.test.client import RequestFactory
from django.conf import settings
import controller
import config
import timer
import collections

import json_utils

# Create your views here.

active_flights = {}
need_refresh = False
num_of_seconds_to_blink = 1 + 3  # 3 seconds
timers = {}
sessions = {}
default_popup_context = {'header': 'Loading... Please Wait',
                         'body': None}


def flight_monitor_js(request):
    template = loader.get_template('flight_monitor/flight_monitor_js.js')
    context = {}
    return HttpResponse(template.render(context, request))


def update_flights_dict():
    global active_flights, timers
    if active_flights is not None and 'status' in active_flights:
        for key, value in active_flights['status'].items():
            print 'value is: ' + str(value)
            print 'blink is at: ' + str(value['blink'])
            if value['blink'] > 0:
                value['blink'] -= 1
            value['time_elapsed'] = timers[key].get_time()


def update_flight_table(request):
    global active_flights, need_refresh
    controller.get_instance().set_current_page(config.CURRENT_PAGE_FLIGHT_MONITOR)
    template = loader.get_template('flight_monitor/flight_monitor_table_update.html')
    update_flights_dict()
    context = active_flights
    controller.get_instance().get_flight_msg()
    return render(request, 'flight_monitor/flight_monitor_table_update.html', context)


def pop_up_modal(request):
    global active_flights, sessions
    drone_num = int(request.POST['drone_num'])
    if not request.session.session_key:
        request.session.save()
    session_id = request.session.session_key
    sessions[session_id] = {'drone_num': drone_num,
                            'context': None}
    return HttpResponse(status=444)


def pop_up_modal_header(request):
    global active_flights, default_popup_context, sessions
    session_id = request.session.session_key
    context = default_popup_context.copy()
    template = loader.get_template('flight_monitor/pop_up_modal_title.html')
    try:
        if sessions[session_id]['drone_num'] < 256:
            context['header'] = 'log for drone number: ' + str(sessions[session_id]['drone_num'])
            sessions[session_id]['context'] = context
    finally:
        return HttpResponse(template.render(context, request))


def pop_up_modal_body(request):
    global active_flights, default_popup_context, sessions
    session_id = request.session.session_key
    context = default_popup_context.copy()
    template = loader.get_template('flight_monitor/pop_up_modal_body.html')
    try:
        if sessions[session_id]['drone_num'] < 256:
            log = 'ERROR IN LOG FILE'
            if 'status' in active_flights:
                for key, value in active_flights['status'].items():
                    if value['drone_num'] == sessions[session_id]['drone_num']:
                        log_path = value['log_path']
                        with open(log_path, 'r') as log_file:
                            log = log_file.read()
                            break
                context['body'] = log
                sessions[session_id]['context'] = context
    finally:
        return HttpResponse(template.render(context, request))


def pop_up_modal_close(request):
    global active_flights, sessions, default_popup_context
    session_id = request.session.session_key
    template = loader.get_template('flight_monitor/flight_monitor.html')
    try:
        se = sessions
        de = default_popup_context
        sessions[session_id]['drone_num'] = 300
        sessions[session_id]['context'] = default_popup_context.copy()
    finally:
        return HttpResponse(template.render(default_popup_context.copy(), request))


def flight_monitor(request):
    global active_flights, need_refresh
    controller.get_instance().set_current_page(config.CURRENT_PAGE_FLIGHT_MONITOR)
    template = loader.get_template('flight_monitor/flight_monitor.html')
    update_flights_dict()
    context = active_flights
    print 'active_flights refresh: ' + str(context)
    return HttpResponse(template.render(context, request))


def refresh_active_flights(flight_status):
    global active_flights, num_of_seconds_to_blink, timers
    if type(flight_status) is dict and 'status' in flight_status:
        active_flights = flight_status
        for key, value in active_flights['status'].items():
            if value['is_updated']:
                value['blink'] = num_of_seconds_to_blink
            if key not in timers or value['cmd'] == 'takeoff':
                timers[key] = timer.Timer(value['start_time'])
            if value['cmd'] == 'landed':
                timers[key].stop_timer()
            value['time_elapsed'] = timers[key].get_time()
        print 'got new flights'


def save_comment(request):
    global active_flights
    try:
        drone_id = int(request.POST['drone_id'])
        comment = request.POST['comment']
        start_time = None
        for key, value in active_flights['status'].items():
            if value['drone_num'] == drone_id:
                start_time = value['start_time']
                break
        response = {'success': False}
        if not start_time or not comment:
            return HttpResponse(json_utils.json_to_str(response), content_type='application/json')
        else:
            msg = {}
            msg['cmd'] = 'query'
            msg['query_num'] = config.QUERY_SAVE_FLIGHT_COMMENT
            msg['drone_id'] = drone_id
            msg['comment'] = comment
            msg['start_time'] = start_time
            result = controller.get_instance().get_system_server().send_msg(msg, blocking=False)
            return HttpResponse(json_utils.json_to_str(response), content_type='application/json')
    except Exception, e:
        print e

finalProjectDjangoWeb1/webserver/flight_monitor/templates/flight_monitor/flight_monitor.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'index/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'index/bootstrap-theme.css' %}">
  <script src="{% static 'index/jquery.min.js' %}"></script>
    <script src="{% static 'index/bootstrap.min.js' %}"></script>
  <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
<title>Drone Page</title>

    <link rel="stylesheet" href="{% static 'index/drone.css' %}">
</head>
<body class="mainBodyFlight1">

<nav>
      <ul>
        <li><a class="menulogo" href="{% url 'index:index' %}"> </a></li>
        <li><a class="menuHome" href="{% url 'index:index' %}"><span class= "titleNav">Home</span></a></li>
        <li><a class="menuFlights" href="{% url 'flight_monitor:flight_monitor' %}"><span class= "titleNavF">Flights</span> </a></li>
        <li><a class="menuReviews" href="{% url 'reviews:reviews' %}"><span class= "titleNav">Reviews</span></a></li>
        <li><a class="menuSetup" href="{% url 'drone_setup:drone_setup' %}"><span class= "titleNav">Setup</span></a></li>
        <li><a class="menuMange" href="{% url 'management:management' %}"><span class= "titleNav">Management</span></a></li>
      </ul>
  </nav>



  <div id="tblDrone">

    <h2 id="title_page">Flight Schedule</h2>

<table id = "flight_tbl" class="table table-striped table-condensed">
  <tr >
    <th>ID</th>
    <th>Ip address</th>
    <th>Status</th>
    <th>Time In Air</th>
    <th>Details</th>

  </tr>
  {% for key, value in status.items %}
  <tr>
    {% if value.blink > 0 %}
      {% if value.is_error %}
        <td class="blinkError" bgcolor="#FF0040"><font color="#FFFFFF"> {{ value.drone_num }}</font></td>
        <td class="blinkError" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.drone_ip }}</font></td>
        <td class="blinkError" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.cmd }}</font></td>
        <td class="blinkError" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.time_elapsed }}</font></td>
        <td class="blinkError" bgcolor="#FF0040"><a style="color:#FFFFFF" class="click-to-show" href="#" data-toggle="modal" data-target="#modalPopUp" onclick="showPopUpForDrone({{ value.drone_num }})">DETAILS</a><button title="Add Comment" class="add_comment" data-toggle="modal" onclick="showCommentPopUp({{ value.drone_num }})"></button></td>
      {% else %}
          <td class="blink"><font color="#0000FF">{{ value.drone_num }}</font></td>
          <td class="blink"><font color="#0000FF">{{ value.drone_ip }}</font></td>
          <td class="blink"><font color="#0000FF">{{ value.cmd }}</font></td>
          <td class="blink"><font color="#0000FF">{{ value.time_elapsed }}</font></td>
          <td class="blink"><a style="color:#0000FF" class="click-to-show" href="#" data-toggle="modal" data-target="#modalPopUp" onclick="showPopUpForDrone({{ value.drone_num }})">DETAILS</a><button title="Add Comment" class="add_comment" data-toggle="modal" onclick="showCommentPopUp({{ value.drone_num }})"></button></td>
      {% endif %}
    {% else %}
      {% if value.is_error %}
        <td class="errorTd" bgcolor="#FF0040"><font color="#FFFFFF"> {{ value.drone_num }}</font></td>
        <td class="errorTd" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.drone_ip }}</font></td>
        <td class="errorTd" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.cmd }}</font></td>
        <td class="errorTd" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.time_elapsed }}</font></td>
        <td class="errorTd" bgcolor="#FF0040"><a style="color: #FFFFFF" class="click-to-show" href="#" data-toggle="modal" data-target="#modalPopUp" onclick="showPopUpForDrone({{ value.drone_num }})">DETAILS</a><button title="Add Comment" class="add_comment" data-toggle="modal" onclick="showCommentPopUp({{ value.drone_num }})"></button></td>
      {% else %}
          <td>{{ value.drone_num }}</td>
          <td>{{ value.drone_ip }}</td>
          <td>{{ value.cmd }}</td>
          <td>{{ value.time_elapsed }}</td>
          <td><a style="color: #000000" class="click-to-show" href="#" data-toggle="modal" data-target="#modalPopUp" onclick="showPopUpForDrone({{ value.drone_num }})">DETAILS</a><button title="Add Comment" class="add_comment" data-toggle="modal" onclick="showCommentPopUp({{ value.drone_num }})"></button></td>
      {% endif %}
    {% endif %}
  </tr>
  {% endfor %}
</table>

</div>

<!-- Modal -->
 <div class="modal fade" id="modalPopUp" role="dialog">
    <div class="modal-dialog modal-lg">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" onclick="closeModal()">&times;</button>
          <h4 class="modal-title" id="modalTitle">Loading... Please Wait</h4>
        </div>
        <div class="modal-body" id="modalBody">
          <p> </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-close" data-dismiss="modal" onclick="closeModal()">Close</button>
        </div>
      </div>
    </div>
  </div>

<!-- Modal -->
 <div class="modal fade" id="addCommentPopUp" role="dialog">


<div class="modal-dialog modal-lg">

      <div class="modal-content">
           <div class="modal-body">
          <button class="close" data-dismiss="modal">×</button>
              <fieldset class ="fieldsetForm_addComment">
                <legend class ="legendForm1">Add comment to flight</legend>
        <div class="modal-body" id="modalBody1">
          <textarea id="text_area" > </textarea>
        </div>
            <button class="addComment_Btn" id="btn_Add_Comment" data-dismiss="modal" onclick="saveFlightComent(text_area.value)">Add</button>
            <button class="cancel_btn"  data-dismiss="modal" onclick="closeModal()">Close</button>

  </fieldset>
      </div>
    </div>

  </div>

  </div>

 <div class="modal fade" id="modal_pop_up_result" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
         <div class="modal-header" id="modal-header">
             <span id="success_title" ></span>
            <button class="close" data-dismiss="modal" onclick="close_result_pop_up()">×</button>


          </div>
          <div class="modal-body">
              <div id="result_body">
                    <span id="success_body" ></span>
              </div>
          </div>
        </div>
      </div>
    </div>

</body>
<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>-->
<script type="text/javascript" src="{% url 'flight_monitor:flight_monitor_js' %}">
</script>
</html>

finalProjectDjangoWeb1/webserver/flight_monitor/templates/flight_monitor/flight_monitor_table_update.html
<div id="tblDrone">

    <h2 id="title_page">Flight Schedule</h2>

<table id = "flight_tbl" class="table table-striped table-condensed">
  <tr >
    <th>ID</th>
    <th>Ip address</th>
    <th>Status</th>
    <th>Time In Air</th>
    <th>Details</th>
  </tr>
  {% for key, value in status.items %}
  <tr>
    {% if value.blink > 0 %}
      {% if value.is_error %}
        <td class="blinkError" bgcolor="#FF0040"><font color="#FFFFFF"> {{ value.drone_num }}</font></td>
        <td class="blinkError" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.drone_ip }}</font></td>
        <td class="blinkError" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.cmd }}</font></td>
        <td class="blinkError" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.time_elapsed }}</font></td>
        <td class="blinkError" bgcolor="#FF0040"><a style="color:#FFFFFF" class="click-to-show" href="#" data-toggle="modal" data-target="#modalPopUp" onclick="showPopUpForDrone({{ value.drone_num }})">DETAILS</a><button title="Add Comment" class="add_comment" data-toggle="modal" onclick="showCommentPopUp({{ value.drone_num }})"></button></td>
      {% else %}
          <td class="blink"><font color="#0000FF">{{ value.drone_num }}</font></td>
          <td class="blink"><font color="#0000FF">{{ value.drone_ip }}</font></td>
          <td class="blink"><font color="#0000FF">{{ value.cmd }}</font></td>
          <td class="blink"><font color="#0000FF">{{ value.time_elapsed }}</font></td>
          <td class="blink"><a style="color:#0000FF" class="click-to-show" href="#" data-toggle="modal" data-target="#modalPopUp" onclick="showPopUpForDrone({{ value.drone_num }})">DETAILS</a><button title="Add Comment" class="add_comment" data-toggle="modal" onclick="showCommentPopUp({{ value.drone_num }})"></button></td>
      {% endif %}
    {% else %}
      {% if value.is_error %}
        <td class="errorTd" bgcolor="#FF0040"><font color="#FFFFFF"> {{ value.drone_num }}</font></td>
        <td class="errorTd" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.drone_ip }}</font></td>
        <td class="errorTd" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.cmd }}</font></td>
        <td class="errorTd" bgcolor="#FF0040"><font color="#FFFFFF">{{ value.time_elapsed }}</font></td>
        <td class="errorTd" bgcolor="#FF0040"><a style="color: #FFFFFF" class="click-to-show" href="#" data-toggle="modal" data-target="#modalPopUp" onclick="showPopUpForDrone({{ value.drone_num }})">DETAILS</a><button title="Add Comment" class="add_comment" data-toggle="modal" onclick="showCommentPopUp({{ value.drone_num }})"></button></td>
      {% else %}
          <td>{{ value.drone_num }}</td>
          <td>{{ value.drone_ip }}</td>
          <td>{{ value.cmd }}</td>
          <td>{{ value.time_elapsed }}</td>
          <td><a style="color: #000000" class="click-to-show" href="#" data-toggle="modal" data-target="#modalPopUp" onclick="showPopUpForDrone({{ value.drone_num }})">DETAILS</a><button title="Add Comment" class="add_comment" data-toggle="modal" onclick="showCommentPopUp({{ value.drone_num }})"></button></td>
      {% endif %}
    {% endif %}
  </tr>
  {% endfor %}
</table>

</div>

finalProjectDjangoWeb1/webserver/flight_monitor/templates/flight_monitor/pop_up_modal_body.html
<div class="modal-body" id="modalBody">
    {% for line in body.splitlines %}
        {% if 'CRITICAL' in line %}
            <p style="color:red;">{{ line }}</p>
        {% elif 'takeoff' in line %}
            <p style="color:blue;">{{ line }}</p>
        {% elif 'landed' in line %}
            <p style="color:green;">{{ line }}</p>
        {% else %}
            <p>{{ line }}</p>
        {% endif %}
    {% endfor %}
</div>

finalProjectDjangoWeb1/webserver/flight_monitor/templates/flight_monitor/pop_up_modal_title.html
<h4 class="modal-title" id="modalTitle">{{ header }}</h4>